name: wallet_hunter
description: "A community-based family registration and management app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Local Storage
  get_storage: ^2.1.1

  # UI Components
  cupertino_icons: ^1.0.2

  # Form Validation
  form_field_validator: ^1.1.0

  # Image Handling
  image_picker: ^1.0.7

  # PDF Generation
  pdf: ^3.10.7
  path_provider: ^2.1.2

  # Date Picker
  flutter_datetime_picker_plus: ^2.1.0

  # Phone Number Input
  intl_phone_field: ^3.2.0

  # Icons
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
